# Environment Configuration
environment:
  name: "CarRacing-v3"
  render_mode: "rgb_array"
  continuous: true
  lap_complete_percent: 0.95

# Model Configuration
model:
  cnn_channels: [3, 32, 64, 64]
  fc_dims: [512, 256]
  learning_rate: 0.0003
  activation: "relu"

# Training Configuration
training:
  num_episodes: 1000
  max_steps_per_episode: 1000
  gamma: 0.99 # discount factor
  gae_lambda: 0.95 # GAE parameter
  clip_ratio: 0.2 # PPO clip ratio
  value_loss_coef: 0.5
  entropy_coef: 0.01
  max_grad_norm: 0.5
  batch_size: 64
  num_epochs: 10
  save_frequency: 100
  log_frequency: 10

# PPO Configuration
ppo:
  clip_range: 0.2
  value_clip_range: 0.2
  num_minibatches: 4
  update_epochs: 4

# Evaluation Configuration
evaluation:
  eval_episodes: 10
  eval_frequency: 50
  render: true
